DROP TABLE IF EXISTS "budget", "reminder", "transaction", "category", "category_type", "friends", "user";


CREATE TABLE "user" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "logo" TEXT
);

CREATE TABLE "friends" (
    "user_id" INT NOT NULL,
    "friend_id" INT NOT NULL,
    "status" SMALLINT NOT NULL,
    PRIMARY KEY ("user_id", "friend_id"),
    FOREIGN KEY ("user_id") REFERENCES "user"("id"),
    FOREIGN KEY ("friend_id") REFERENCES "user"("id")
);

-- 0-expense, 1-income
CREATE TABLE "category_type" (
    "type" BOOLEAN PRIMARY KEY
);

CREATE TABLE "category" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "user_id" INT NOT NULL,
    "type" BOOLEAN NOT NULL,
    FOREIGN KEY ("user_id") REFERENCES "user"("id"),
    FOREIGN KEY ("type") REFERENCES "category_type"("type")
);

CREATE TABLE "transaction" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "amount" NUMERIC(10, 2) NOT NULL,
    "date" TIMESTAMP NOT NULL,
    "category_id" INT NOT NULL,
    FOREIGN KEY ("category_id") REFERENCES "category"("id")
);

CREATE TABLE "reminder" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "amount" NUMERIC(10, 2),
    "due_date" TIMESTAMP NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "is_shared" BOOLEAN NOT NULL DEFAULT FALSE,
    "category_id" INT NOT NULL,
    FOREIGN KEY ("category_id") REFERENCES "category"("id")
);

CREATE TABLE "budget" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "amount" NUMERIC(10, 2),
    "start_date" DATE,
    "end_date" DATE,
    "category_id" INT NOT NULL,
    FOREIGN KEY ("category_id") REFERENCES "category"("id")
);

INSERT INTO "category_type" ("type") VALUES (FALSE), (TRUE) 
ON CONFLICT DO NOTHING;